=== WallofKron/CSUCI_Comp.Sci./CS232 - Programming Languages/Lab4/ciML.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="catalog">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="catalog">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="year">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="semester" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="mjrprogram">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Physics">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="classes" maxOccurs="unbounded" minOccurs="0">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="description">
                                              <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                    <xs:attribute type="xs:string" name="category" use="optional"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                              </xs:complexType>
                                            </xs:element>
                                            <xs:element type="xs:byte" name="unitweight"/>
                                            <xs:element type="xs:string" name="professor"/>
                                            <xs:element name="date">
                                              <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element type="xs:string" name="days"/>
                                                  <xs:element type="xs:string" name="time"/>
                                                </xs:sequence>
                                              </xs:complexType>
                                            </xs:element>
                                          </xs:sequence>
                                          <xs:attribute type="xs:short" name="category" use="optional"/>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="CMPSCI">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="classes" maxOccurs="unbounded" minOccurs="0">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="description">
                                              <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                    <xs:attribute type="xs:string" name="category" use="optional"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                              </xs:complexType>
                                            </xs:element>
                                            <xs:element type="xs:byte" name="unitweight"/>
                                            <xs:element type="xs:string" name="professor"/>
                                            <xs:element name="date">
                                              <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element type="xs:string" name="days"/>
                                                  <xs:element type="xs:string" name="time"/>
                                                </xs:sequence>
                                              </xs:complexType>
                                            </xs:element>
                                          </xs:sequence>
                                          <xs:attribute type="xs:short" name="category" use="optional"/>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Math">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="classes" maxOccurs="unbounded" minOccurs="0">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="description">
                                              <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                    <xs:attribute type="xs:string" name="category" use="optional"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                              </xs:complexType>
                                            </xs:element>
                                            <xs:element type="xs:byte" name="unitweight"/>
                                            <xs:element type="xs:string" name="professor"/>
                                            <xs:element name="date">
                                              <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element type="xs:string" name="days"/>
                                                  <xs:element type="xs:string" name="time"/>
                                                </xs:sequence>
                                              </xs:complexType>
                                            </xs:element>
                                          </xs:sequence>
                                          <xs:attribute type="xs:short" name="category" use="optional"/>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="category" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:short" name="year"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== WallofKron/CSUCI_Comp.Sci./CS232 - Programming Languages/Lab4/catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ciML.xsd">
 <catalog>
	<year year="2015">
		<semester category="Fall">
			<mjrprogram>
				<Physics>
					<classes category="100">
						<description category="A non-calculus based intro to physics. Classical mechanics, wave motion and thermal physics"></description>
						<unitweight>4</unitweight>
						<professor>David Nelson</professor>
						<date>
							<days>TTH</days>
							<time>10:30-11:45</time>
						</date>
					</classes>
					<classes category="101">
						<description category="A non-calculus based intro to physics. Electromagnetic theory, light, and atomic and nuclear physics"></description>
						<unitweight>4</unitweight>
						<professor>William Barber</professor>
						<date>
							<days>T</days>
							<time>6:00-8:50</time>
						</date>
					</classes>
					<classes category="200">
						<description category="A calculus-based intro to physics. Classical mechanics, wave motion and thermal physics"></description>
						<unitweight>4</unitweight>
						<professor>Gregory Wood</professor>
						<date>
							<days>MW</days>
							<time>1:30-2:45</time>
						</date>
					</classes>
					<classes category="201">
						<description category="A calculus-based intro to physics. Electromagnetic theory, light, and atomic and nuclear physics"></description>
						<unitweight>4</unitweight>
						<professor>Clinton Harper</professor>
						<date>
							<days>TTH</days>
							<time>12:00-1:00</time>
						</date>
					</classes>
					<classes category="306">
						<description category="Special relativity, the Bohr model, Quantum mechanics; photons, the photoelectric effect, probability density, matter waves, Schrodinger mechanics, the Uncertainty Principle,"></description>
						<unitweight>3</unitweight>
						<professor>Gregory Wood</professor>
						<date>
							<days>MW</days>
							<time>1:30-2:45</time>
						</date>
					</classes>
				</Physics>

				<CMPSCI>
					<classes category="454">
						<description category="Study of the relation of languages and machines for processing these languages, with emphasis on classes of languages and corresponding classes of machines"></description>
						<unitweight>3</unitweight>
						<professor>Micheal Soltys</professor>
						<date>
							<days>MW</days>
							<time>12:00-1:15</time>
						</date>
					</classes>
					<classes category="221">
						<description category="Fundamentals of the UNIX o.s., including the command line interface, shell commands"></description>
						<unitweight>3</unitweight>
						<professor>Ronald Rieger</professor>
						<date>
							<days>M</days>
							<time>6:00-7:50</time>
						</date>
					</classes>
					<classes category="150">
						<description category="Discussion of issues in design, implementation, and use of high-level prog. langs"></description>
						<unitweight>4</unitweight>
						<professor>Jason Isaacs</professor>
						<date>
							<days>T</days>
							<time>12:00-2:50</time>
						</date>
					</classes>
					<classes category="232">
						<description category="Discussion of issues in design, implementation, and use of high-level prog. langs"></description>
						<unitweight>3</unitweight>
						<professor>Kevin Scrivnor</professor>
						<date>
							<days>TTH</days>
							<time>12:00-1:50</time>
						</date>
					</classes>
					<classes category="345">
						<description category="An intro to the basic concepts and techniques for digital image restoration and enhancement, analysis, coding and compression"></description>
						<unitweight>3</unitweight>
						<professor>Geoffrey Doughtery</professor>
						<date>
							<days>MW</days>
							<time>12:00-1:15</time>
						</date>
					</classes>
				</CMPSCI>

				<Math>
					<classes category="150">
						<description category="A course in analytic geometry and calculus"></description>
						<unitweight>4</unitweight>
						<professor>Brian Sittinger</professor>
						<date>
							<days>MW</days>
							<time>10:00-11:50</time>
						</date>
					</classes>
					<classes category="151">
						<description category="Differentiation, integration, sequences, infinite series, and power series"></description>
						<unitweight>4</unitweight>
						<professor>Peter Yi</professor>
						<date>
							<days>TTH</days>
							<time>8:00-9:50</time>
						</date>
					</classes>
					<classes category="250">
						<description category="functions of several variables, solid analytic geometry, partial differentiation, multiple integrals with applications; vector analysis, and line and surface integrals"></description>
						<unitweight>3</unitweight>
						<professor>Cynthia Wyels</professor>
						<date>
							<days>TTH</days>
							<time>9:00-10:15</time>
						</date>
					</classes>
					<classes category="350">
						<description category="ordinary differential equations, existence and uniqueness of solutions. Linear equations. Laplace methods. Flows and diffeomorphisms, limit sets, iterations of maps. Positive entropy systems, chaotic behavior of trajectories"></description>
						<unitweight>3</unitweight>
						<professor>Cynthia Flores</professor>
						<date>
							<days>MW</days>
							<time>12:00-1:15</time>
						</date>
					</classes>
                    <classes category="240">
						<description category="Matrices, linear systems of equations, determinants, vectors in 2 and 3 dimensions, eigenvalues, the vector space Rn, linear transformations, introduction to general vector spaces and applications"></description>
						<unitweight>3</unitweight>
						<professor>Selenne Banuelos</professor>
						<date>
							<days>TTH</days>
							<time>12:00-1:15</time>
						</date>
					</classes>
				</Math>		

			</mjrprogram>
		</semester>
		<semester category="Spring">
			<mjrprogram>
				<Physics>
					<classes category="100">
						<description category="A non-calculus based intro to physics. Classical mechanics, wave motion and thermal physics"></description>
						<unitweight>4</unitweight>
						<professor>David Nelson</professor>
						<date>
							<days>TTH</days>
							<time>1:30-2:45</time>
						</date>
					</classes>
					<classes category="101">
						<description category="A non-calculus based intro to physics. Electromagnetic theory, light, and atomic and nuclear physics"></description>
						<unitweight>4</unitweight>
						<professor>Dale Capewell</professor>
						<date>
							<days>MW</days>
							<time>4:30-5:45</time>
						</date>
					</classes>
					<classes category="200">
						<description category="A calculus-based intro to physics. Classical mechanics, wave motion and thermal physics"></description>
						<unitweight>4</unitweight>
						<professor>Clinton Harper</professor>
						<date>
							<days>TTH</days>
							<time>12:00-1:15</time>
						</date>
					</classes>
					<classes category="201">
						<description category="A calculus-based intro to physics. Electromagnetic theory, light, and atomic and nuclear physics"></description>
						<unitweight>4</unitweight>
						<professor>Gregory Wood</professor>
						<date>
							<days>MW</days>
							<time>1:30-2:45</time>
						</date>
					</classes>
					<classes category="400">
						<description category="innovative approach to quantum physics by combining the essential elements of the theory with the practical applications. Applications include Raman spectroscopy, scanning tunnelling microscopy, quantum optics, quantum cryptography and quantum computing"></description>
						<unitweight>3</unitweight>
						<professor>Gregory Wood</professor>
						<date>
							<days>MW</days>
							<time>4:30-5:45</time>
						</date>
					</classes>
				</Physics>

				<CMPSCI>
					<classes category="445">
						<description category="Pattern recognition consists of image segmentation, feature extraction and classification. The principles and concepts underpinning pattern recognition, and the evolution, utility and limitations of various techniques (including neural networks) will be studied"></description>
						<unitweight>3</unitweight>
						<professor> Geoffrey Doughtery</professor>
						<date>
							<days>MW</days>
							<time>12:00-1:15</time>
						</date>
					</classes>
					<classes category="221">
						<description category="Fundamentals of the UNIX o.s., including the command line interface, shell commands"></description>
						<unitweight>3</unitweight>
						<professor>Ronald Rieger</professor>
						<date>
							<days>T</days>
							<time>6:00-7:50</time>
						</date>
					</classes>
					<classes category="150">
						<description category="Discussion of issues in design, implementation, and use of high-level prog. langs"></description>
						<unitweight>4</unitweight>
						<professor>Justin Pearson</professor>
						<date>
							<days>T</days>
							<time>12:00-2:50</time>
						</date>
					</classes>
					<classes category="232">
						<description category="Discussion of issues in design, implementation, and use of high-level prog. langs"></description>
						<unitweight>3</unitweight>
						<professor>Andrej Bieszczad</professor>
						<date>
							<days>TTH</days>
							<time>12:00-1:50</time>
						</date>
					</classes>
					<classes category="342">
						<description category="Explores the ongoing evolution of Internet based social networks using an interdisciplinary approach. Incorporates research from sociology, computer science, media studies, and philosophy to understand Internet based social networks, cultural and structural conditions of online communication, virtual identity construction, management of digital media, and the impact online social networks have on various institutions of society"></description>
						<unitweight>3</unitweight>
						<professor>Brian Thoms</professor>
						<date>
							<days>MW</days>
							<time>4:30-5:45</time>
						</date>
